1  name: TOOLBOXLAP- LiteManager
2
3  on:
4    workflow_dispatch:
5
6  jobs:
7    build:
8      name: Start Building...
9      runs-on: windows-2019
10     timeout-minutes: 9999
11
12     steps:
13       - name: Downloading & Installing Essentials
14         run: |
15           Invoke-WebRequest -Uri "https://raw.githubusercontent.com/tollboxlap09/tollboxlap09/refs/heads/main/Downloads.bat" -OutFile "Downloads.bat"
16           cmd /c Downloads.bat
17
18       - name: TOOLBOXLAP
19         run: cmd /c show.bat
20
21       - name: like and subscribe
22         run: cmd /c loop.bat
